# Generated by Django 5.0.4 on 2024-06-03 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
