# Generated by Django 5.0.4 on 2024-05-22 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='timestamp',
        ),
    ]
