# Generated by Django 5.0.4 on 2024-05-25 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crud_update_notification',
            old_name='changed_fields',
            new_name='field_with_addition',
        ),
        migrations.RenameField(
            model_name='crud_update_notification',
            old_name='object_json_repr',
            new_name='instance_basic_fields_str',
        ),
        migrations.RenameField(
            model_name='crud_update_notification',
            old_name='object_repr',
            new_name='instance_name_str',
        ),
        migrations.RemoveField(
            model_name='crud_update_notification',
            name='user_pk_as_string',
        ),
    ]
