# Generated by Django 5.0.4 on 2024-04-25 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_delete_campaignepisodes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image_url',
            field=models.CharField(blank=True, default='static/images/default_profile_pic.png', max_length=2083, null=True),
        ),
    ]
