# Generated by Django 5.0.4 on 2024-05-25 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_rename_changed_fields_crud_update_notification_field_with_addition_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crud_update_notification',
            old_name='object_id',
            new_name='updated_instance_id',
        ),
    ]
