# Generated by Django 5.0.4 on 2024-06-04 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_alter_notification_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='added_instance_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='updated_obj_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
