# Generated by Django 5.0.4 on 2024-06-04 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_notification_added_instance_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='added_instance_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='updated_obj_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
