# Generated by Django 5.0.4 on 2024-05-25 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_rename_object_id_crud_update_notification_updated_instance_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='crud_update_notification',
            name='read_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='crud_update_notification',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.profile'),
        ),
        migrations.AddField(
            model_name='crud_update_notification',
            name='subject',
            field=models.CharField(default='[Subject]', max_length=50),
        ),
    ]
