# Generated by Django 5.0.4 on 2024-06-03 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_crud_update_notification_read_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='receiver',
        ),
        migrations.DeleteModel(
            name='CRUD_Update_Notification',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
