# Generated by Django 5.0.4 on 2024-05-06 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_rename_guests_campaign_guest_pcs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
