# Generated by Django 5.0.4 on 2024-05-22 06:23

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_alter_notification_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='CRUD_Update_Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.IntegerField(blank=True, null=True)),
                ('object_repr', models.CharField(blank=True, max_length=500, null=True)),
                ('object_json_repr', models.CharField(blank=True, max_length=500, null=True)),
                ('changed_fields', models.CharField(blank=True, max_length=500, null=True)),
                ('content_type_id', models.IntegerField(blank=True, null=True)),
                ('object_id', models.IntegerField(blank=True, null=True)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('datetime', models.DateTimeField(blank=True, null=True)),
                ('user_pk_as_string', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'CRUD Update Notification',
            },
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=ckeditor.fields.RichTextField(blank=True, max_length=5000, null=True),
        ),
    ]
