# Generated by Django 5.0.4 on 2024-05-22 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_crud_update_notification_alter_notification_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crud_update_notification',
            name='changed_fields',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='crud_update_notification',
            name='event_type',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='crud_update_notification',
            name='object_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='crud_update_notification',
            name='object_json_repr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='crud_update_notification',
            name='object_repr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='crud_update_notification',
            name='user_pk_as_string',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
